### ISSUE TITLE
API Functions Needed - job_selection.html

### ISSUE THREAD

**Issue by zbirmingham** [spapali/Blue-Economics#11]
We need these API functions from the index.php file (I'll continue to update this issue as we progress):

job-selection.html functions

/industries - (already created) populates all industries from `industries` table, this may require some cleaning up

/jobs - (already created) populates all jobs from `occupations` table, can accept variable via $_GET to query MySQL database for specific industry identifier, this may require some cleaning up

/job_description - (already created, doesn't work) query `occupations` table for specific Job (column heading), Description (column heading), MedianPayAnnual (column heading), MedianPayHourly (column heading), NumberOfJobs (column heading), EmploymentOpenings via String Variable passed via $_GET

A function that can accept a query from the front end that is maybe tied into /job_description that can provide the user with Name (column heading) from `workexperiences` table when provided with WorkExperienceId (column heading) from `occupations` table. **Question[obraafo]: Are you asking for a function that returns work experience name given an id?** 

A function that takes a string from the form on the job-selection.html page and queries the `industry` and `occupations` tables for a corresponding match. **Question[obraafo]: What is return for a match?**

A function that is triggered from the front-end (education checkbox) and filters the results from the `occupations` tables based on the EmploymentLevelId (column heading) and then will filter the corresponding results from the `industry` table. **Question[obraafo]: Are you expecting this api to return the list of industries and jobs as one resultset?**

**Comment by zbirmingham** [comment]
A function that can accept a query from the front end that is maybe tied into /job_description that can provide the user with Name (column heading) from `workexperiences` table when provided with WorkExperienceId (column heading) from occupations table. Question[obraafo]: Are you asking for a function that returns work experience name given an id?
- Right, the WorkExperienceId (column heading) from the occupations table will correspond with the Id (column heading) in the `workexperiences` table and the end result is that the function will return the string from the Name (column heading) in the `workexperiences` table.

A function that takes a string from the form on the job-selection.html page and queries the industry and occupations tables for a corresponding match. Question[obraafo]: What is return for a match? 
- Sorry, didn't do a great job of describing this one. This is essentially the search function, not sure if a specific one needs to be written for this page. Essentially when it searches, I want to give me back the Name (column heading) from the `industry` table and Name (column heading) from the `occupations` table.

A function that is triggered from the front-end (education checkbox) and filters the results from the `occupations` tables based on the EmploymentLevelId (column heading) and then will filter the corresponding results from the industry table. Question[obraafo]: Are you expecting this api to return the list of industries and jobs as one resultset? 
- Is it possible to get back 2 separate results? Essentially, it should echo the results as 2 separate results that will hit 2 separate divs on the front end. Not sure if this needs to be 2 different functions.

**Comment by dasibre** [comment]
Would it be possible to probably use the wiki section instead of the issues section of the repo for the request specifications? And use issues for actual issues/bugs found in the application? 

Also, the language for the features are sooo confusing, maybe i'm just dumb. If I may suggest us using just plain old english for describing features.

e.g 
A function that is triggered from the front-end (education checkbox) and filters the results from the occupations tables based on the EmploymentLevelId (column heading) and then will filter the corresponding results from the industry table. TOO TECHNICAL AND CONFUSING

Plain-english:API should return the list of industries and jobs as,(a bit simplistic but, easier to read and understand)

**Comment by spapali** [comment]
I think we can make those adjustments about the move to the wiki section unless Zack has a problem with it. I think Zack made the API descriptions really detailed so that there would be less questions back and forth. Do we need a simpler explanation of the current API requests or moving forward?

**Comment by zbirmingham** [comment]
@obraafo, I just wanted it to be really clear what information should come from what table and how they all relate. I'm happy to more simply describe what information I am looking for.

**Comment by spapali** [comment]
Thanks Zack. I think were all on the same page just lost in translation

**Comment by zbirmingham** [comment]
Also @obraafo, was thinking maybe we can just leave the current API issues list and then any API functions we need going forward we can add in the wiki?

**Comment by spapali** [comment]
I'm comfortable with that Zack if James and George don't mind.

**Comment by obraafo** [comment]
@zbirmingham the requested changes have been committed to the `jobs_apis` branch and merged into the `master` branch. Please review and let me know if anything is missing.

NB: It's not clear to me how you want to use the results of the search query, so I'm currently just logging to the console and refreshing the jobs list panel ( probably needs to update the industries as well ).

**Comment by zbirmingham** [comment]
@obraafo, wanted to clarify how the search should work. Technically it should be an AJAX call that queries the information in the Industry and Jobs columns on the front end as the user is typing. So for example as the user types "Nursing" the Jobs column should display "Nursing Aides, Orderlies, and Attendants" and "Healthcare Support Occupations" should be displayed in the Industry column because that corresponds to the match for Nursing in jobs. So wherever the search can make a match in the `industries` table or `occupations` table. It should display the corresponding results in those 2 columns.
