### ISSUE TITLE
`growthscores` table has no data

### ISSUE THREAD

**Issue by zbirmingham** [spapali/Blue-Economics#13]
I was going through the data in the BlueEconomics database and noticed there's nothing in table. I'm assuming this is where the scores for each job were supposed to go. Not sure what we need to do to fix this, not sure if there's data somewhere existing already.

**Comment by spapali** [comment]
I'll have to dig it up. I have it somewhere.

**Comment by diael01** [comment]
Hi Sujith,
Elena here. I have to apologize, I did not have much time to contribute to the project.
Please take me out of the list.
I will get back to this project when/if I finish my other projects.
Thank you and good week-end, I much appreciate your initial invitation.
Elena

**Comment by spapali** [comment]
No worries.  Completely understand. I've asked david to remove you.
