### ISSUE TITLE
Original Data reconciliation

### ISSUE THREAD

**Issue by spapali** [spapali/Blue-Economics#14]
Need to reconcile data currently being used in the website with correct data

**Comment by zbirmingham** [comment]
Seems to be an issue with `occupations` table. It's almost 26,000 lines of data, a lot of which are duplicates.

**Comment by spapali** [comment]
Thanks Zack! Let me look at this

**Comment by spapali** [comment]
Looked at the data. The data is definetly wrong. Theres about 2500 duplicates. The correct data can be found the Excel Spreadsheet in DropBox Blue Econ Final Data and Scores 4212013. There should be 680 Occupations. The Job Descriptions are from an XML pull that needs to be merged to the Excel spreadsheet.

**Comment by spapali** [comment]
The Excel file “Blue Econ Final Data and Scores 4212013 breakdown key:
Use “All_Scores” tab
Education Level: Entry Level Education Required (per Bureau of Labor Statistics) (Column L)
Annual Income: Median (Column R) **\* divide by 2000 for hourly rate
Score or Rating: Level (Column I)

The tab “Salary NY” has the map for Industry,
Column J is the “Industry ID” which can be mapped to the SOC ID in Column A in
the “All_Scores” ID. The first two digits represent the “Industry ID” in the SOC ID.
Example: Chief Executives SOC ID: 11-1011
    11 is the “Industry ID” and it is mapped to Management occupations
This

**Comment by obraafo** [comment]
@spapali What's the source of the NumberOfJobs and EmploymentOpenings data?

**Comment by spapali** [comment]
All data is from the State department of labor and Bureu of labor stats.

**Comment by obraafo** [comment]
Meant, what column/tab of the spreadsheet is the data from. You didn't indicate in your explanation, but it's already in the database and displayed in results.

**Comment by spapali** [comment]
Sorry I got you. I'm not at home and don't have access to the spreadsheet. I'll get this to you early tomorrw

**Comment by spapali** [comment]
Number of Jobs would be Column P: "Employment"
EmploymentOpenings would be Column K: "Annual Average Openings"

**Comment by zbirmingham** [comment]
Who should be assigned to update the MySQL data, dump the data and commit a new SQL file?
