### ISSUE TITLE
Different File for MySQL Username and Password

### ISSUE THREAD

**Issue by zbirmingham** [spapali/Blue-Economics#16]
This isn't necessarily an issue right now, but when we push this to production we'll need to include a different file for the MySQL connection in the API. @obraafo I saw that you had included that mysql.ini file for local development, but @jemuelyoung had created a different file with the username and password for the remote server.

**Comment by obraafo** [comment]
fixed by commit #565e97f701492bae61ca9bf05b372518892e6c77
