### ISSUE TITLE
Index.html Video Background Not Working

### ISSUE THREAD

**Issue by zbirmingham** [spapali/Blue-Economics#20]
Not sure why this stopped working, I need to take a look into this.

**Comment by zbirmingham** [comment]
I committed  `/media/movies/Video_02-1080-Filter2.mp4` to try and address this issue. It's mainly Chrome because it doesn't seem like Chrome really supports HTML5 video anymore. Find a solution specifically for Chrome or we can find a new overall solution for the landing page.

**Comment by jakubzapletal** [comment]
I use Chrome and the video works for me.

**Comment by zbirmingham** [comment]
I think it depends on which version of Chrome you are using. I think certain versions support HTML5 video and others don't. When I open the site in literally any other browser it works great. This isn't really something we need to worry about right now, but something I wanted to call out for down the road.

**Comment by jakubzapletal** [comment]
I agree. There is a table of browser support http://en.wikipedia.org/wiki/HTML5_video. You can use multiple sources as shown in example. It might solve the issue.

**Comment by zbirmingham** [comment]
We're definitely using multiple sources, doesn't seem to solve the problem in all version of Chrome though.

```
<video width="auto" height="120%" loop autoplay="autoplay" muted poster="/media/images/Video_02-1080-Filter2.jpg" preload="none">
    <source src="/media/movies/Video_02-1080-Filter2.webm" type="video/webm">
    <source src="/media/movies/Video_02-1080-Filter2.ogv" type="video/ogg">
    <source src="/media/movies/Video_02-1080-Filter2.m4v" type="video/mp4">
            Your browser does not support the video tag.
</video>
```

Thought using the MP4 video would help, but it doesn't. I'm using Version 35.0.1916.153 of Chrome and it defaults to the wallpaper every time.

Just worried that using video might be a wildcard though that's going to show up differently in all of the browsers. Ultimately, what I am suggesting is that maybe we move away from this entirely and come up with a solution that's equally visually impressive, but more stable. Unless we can come up with a better solution.
