### ISSUE TITLE
/search/ function not returning industry results

### ISSUE THREAD

**Issue by zbirmingham** [spapali/Blue-Economics#24]
@obraafo, not sure if this is an issue with the mysql database or the actual /search/ function, but when I hit the /search/ API function it's only returning the job results.

For example, when I do a search for nurses, I'm getting this back:
{"industries":[],"jobs":[{"name":"Licensed Practical and Licensed Vocational Nurses"},{"name":"Registered Nurses"},{"name":"Surgical Technologists"}]}

**Comment by obraafo** [comment]
fix by commmit
