### ISSUE TITLE
Text Response via Get

### ISSUE THREAD

**Issue by zbirmingham** [spapali/Blue-Economics#48]
I'm a little concerned about the `add_response_from_question` API function. This function is designed to receive a text response to a users question from an expert and the text that's part of this response is being sent in the URL. I don't really feel like this is the right approach.

**Comment by zbirmingham** [comment]
@young can you take a look at this?

**Comment by young** [comment]
Yeah that should be a POST request instead of a GET. I'll convert it over.

**Comment by young** [comment]
https://github.com/innls/Blue-Economics/pull/49
