### ISSUE TITLE
Set up of working instance of MYSQL

### ISSUE THREAD

**Issue by spapali** [spapali/Blue-Economics#5]

**Comment by young** [comment]
This is done. Ping me if you need MySQL access.

**Comment by young** [comment]
Here is the login information for MySql. I disabled remote access so everyone must ssh in to access the database.

Email me for the mysql credentials.

I recommend [MySQL Workbench](http://dev.mysql.com/downloads/tools/workbench/) for Windows users and [Sequel Pro](http://www.sequelpro.com/download) for OSX users.

![mysql](https://f.cloud.github.com/assets/984983/2433103/ce752c94-ad81-11e3-95b2-9f81b9c4cce1.png)

**Comment by zbirmingham** [comment]
@jemuelyoung I'm having an issue connecting via SSH into the server. This is what I am plugging into Sequel Pro:
![screen shot 2014-03-17 at 7 26 23 pm](https://f.cloud.github.com/assets/3819575/2442985/f88e3a52-ae2b-11e3-945a-7a9216f8aee3.png)

Not sure if it helps, this is the error message I'm getting:
![screen shot 2014-03-17 at 7 26 56 pm](https://f.cloud.github.com/assets/3819575/2442987/06854ac4-ae2c-11e3-9ffc-2a3fb0f345ea.png)

Am I doing something wrong?

**Comment by young** [comment]
The SSH Host should just be: 54.83.62.231

You also need the password for the blue_econ user which is on dropbox under the "Dev" folder.

**Comment by young** [comment]
@zbirmingham let me know if you have any more problems

**Comment by zbirmingham** [comment]
Realized I didn't post that whole error message

![screen shot 2014-03-17 at 9 26 29 pm](https://f.cloud.github.com/assets/3819575/2443680/6c62aa16-ae3c-11e3-8786-be5964c078ea.png)

**Comment by young** [comment]
@zbirmingham  Sent you an email
