### ISSUE TITLE
Technology choice - language, data store

### ISSUE THREAD

**Issue by greendost** [spapali/Blue-Economics#7]

**Comment by spapali** [comment]
awesome that was quick

**Comment by greendost** [comment]
I wonder if a table approach would work.. something like this...
maybe a spreadsheet might be better to hold final thoughts

| Language | Harteg | Jemuel | Sujith |
| --- | --- | --- | --- |
| c# |  |  |  |
| java |  |  |  |
| ruby |  |  |  |
| php |  |  |  |
| python |  |  |  |
| node.js |  |  |  |
| scala |  |  |  |

| Data Store | Harteg | Jemuel | Sujith |
| --- | --- | --- | --- |
| mongodb |  |  |  |
| mysql |  |  |  |
| postgresql |  |  |  |
| riak |  |  |  |

**Comment by greendost** [comment]
Ok, just opened an issue, and tried adding a table - I think the spreadsheet 
might be good to summarize all our thoughts after we post in the issue.  So I
will add my thoughts to the issue now.

On Sunday, March 16, 2014 6:11 PM, spapali notifications@github.com wrote:

Reopened #7.

**Comment by spapali** [comment]
this looks good

**Comment by greendost** [comment]
I have practically no experience with any of these languages or data stores, so I am ok with whatever we pick.  But these are things I have heard (tech opinions or read).  

| language | comment |
| --- | --- |
| c# | ? |
| java | Tried and true, strongly typed, but no REPL and seems like a heavyweight language |
| ruby | popular |
| php | "Used by Facebook and Wordpress.  I have heard concerns over readability, but new language features probably mitigate that." |
| python | readable |
| node.js | "Article in last month's ACM where LinkedIn chose to replace a Ruby-based system with Node.  https://queue.acm.org/detail.cfm?id=2567673  Also used in Microsoft's Azure Cloud Service" |
| scala | "Used by Twitter.  There are two web frameworks I have heard of - Akka and Lift.  Language may be hard to learn. |

| data store | comment |
| --- | --- |
| mongodb |  |
| mysql | Used by Facebook |
| postgresql | I think this is open source too. |
| riak | ? |

**Comment by spapali** [comment]
hey thats a real nice primer. im thinking we go mysql and php but the above is a great starting point

**Comment by diael01** [comment]
Ruby and Mongodb
