### ISSUE TITLE
Understand BigVideo.js for Landing Page

### ISSUE THREAD

**Issue by zbirmingham** [spapali/Blue-Economics#9]
For some reason this seems to only work on Chrome. Might have to implement HTML 5 video tag.

**Comment by spapali** [comment]
Zack will send Rose two or three videos for the main page to compress using video editing software to speed up the videos. Zack, Rose and I will experiment with filters and other designs to perfect the main landing page.

**Comment by zbirmingham** [comment]
@rosebery19 I uploaded the videos into the dropbox in the 'Movies' folder, take a look when you get a chance

**Comment by rosebery19** [comment]
Thanks Zack, will take a look.

Rose

On Tue, Mar 25, 2014 at 10:48 PM, Zack Birmingham
notifications@github.comwrote:

> @rosebery19 https://github.com/rosebery19 I uploaded the videos into
> the dropbox in the 'Movies' folder, take a look when you get a chance
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/innls/Blue-Economics/issues/9#issuecomment-38645008
> .

## 

Rose Naves, MFA

**Comment by rosebery19** [comment]
Hi All, I placed the compressed videos in the Movies > Edited folders. you
can also view from web here:
https://www.dropbox.com/sh/b5io23yemb1slfx/COSjWNGwSl

Placed some blur effects and reduced time to 10 seconds. Let me know what
you think.

Rose

On Tue, Mar 25, 2014 at 11:33 PM, Rose Naves rosebery19@gmail.com wrote:

> Thanks Zack, will take a look.
> 
> Rose
> 
> On Tue, Mar 25, 2014 at 10:48 PM, Zack Birmingham <
> notifications@github.com> wrote:
> 
> > @rosebery19 https://github.com/rosebery19 I uploaded the videos into
> > the dropbox in the 'Movies' folder, take a look when you get a chance
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/innls/Blue-Economics/issues/9#issuecomment-38645008
> > .
> 
> ## 
> 
> Rose Naves, MFA

## 

Rose Naves, MFA

**Comment by zbirmingham** [comment]
Thanks @rosebery19, I'll try them out.

**Comment by zbirmingham** [comment]
So, I created something on my site so we can test and see the videos.
It's all done with HTML 5 video and it's responsive!

http://zbirminghamdesign.com/tests/Movies/index.html

Username: sujith
Password: P@$$w0rd

Let me know what you think.

**Comment by spapali** [comment]
Pretty awesome. Quick too
